export const ERROR_CODES = {
    USER: {
        NOT_FOUND: "USER_NOT_FOUND",
        ALREADY_EXISTS: "USER_ALREADY_EXISTS",
        INVALID_CREDENTIALS: "USER_INVALID_CREDENTIALS",
        INVALID_EMAIL: "USER_INVALID_EMAIL",
    },
};
